{% set name = "cool.io" %}
{% set version = "1.7.0" %}

package: 
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 04cf9c8fc6624566765044ed617df22675ba6998494d0d568e9e0d7bc5d3d6ee

build:
  number: 0
  script:
    # -N don't generate documentation
    # -l restrict ops to local domain ???
    # -V verbosity
    # --norc Avoid loading any .gemrc file
    # --ignore-deps Do not install any required dependent gems

    # https://github.com/conda-forge/compilers-feedstock/issues/6
    # https://github.com/ContinuumIO/anaconda-issues/issues/9863
    # https://stackoverflow.com/questions/51640663/developer-tools-issues-when-installing-ruby-gems
    # logging for help
    # - xcode-select -p  # [osx]
    # - echo "$CONDA_BUILD_SYSROOT"  # [osx]
    # - echo "$SDKROOT"  # [osx]
    - echo "LISTING PKG_CONFIG_PATH"  # [osx]
    - echo "$PKG_CONFIG_PATH"  # [osx]

    - gem install -N -l -V --norc --ignore-dependencies --backtrace {{ name }}-{{ version }}.gem --
      # --with-xml2-include=/Applications/Xcode_11.7.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/libxml2
      --use-system-libraries
      --without-opt-dir
      --with-opt-lib

    # - gem unpack {{ name }}-{{ version }}.gem

    # - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    #   {%- for e in [ "cool.io", "iobuffer" ] -%}
    #   && make -C {{ PREFIX }}/lib/ruby/gems/{{ ruby }}.0/gems/{{ name }}-{{ version }}/ext/{{ e }} clean
    #   {%- endfor -%}
    #   && gem unpack {{ name }}-{{ version }}.gem
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler("cxx") }}
  host:
    - ruby
    - ruby
    - openssl
    - libxml2
    - libxslt
    - rb-pkg-config
  run:
    - ruby

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT & BSD-2-Clause
  license_file: LICENSE
  summary: Cool.io provides a high performance event framework for Ruby which uses the libev C library
  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/tarcieri/cool.io

extra:
  recipe-maintainers:
    - oblute
    - benhuff
    - sodre
