{% set name = "cool.io" %}
{% set version = "1.7.0" %}

package: 
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 04cf9c8fc6624566765044ed617df22675ba6998494d0d568e9e0d7bc5d3d6ee

build:
  number: 0
  script:
    # -N don't generate documentation
    # -l restrict ops to local domain ???
    # -V verbosity
    # --norc Avoid loading any .gemrc file
    # --ignore-deps Do not install any required dependent gems

    # https://github.com/conda-forge/compilers-feedstock/issues/6
    # https://github.com/ContinuumIO/anaconda-issues/issues/9863
    - xcode-select -p  # [osx]
    - echo "$CONDA_BUILD_SYSROOT"  # [osx]
    - echo "$SDKROOT"  # [osx]
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem

    # - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    #   {%- for e in [ "cool.io", "iobuffer" ] -%}
    #   && make -C {{ PREFIX }}/lib/ruby/gems/{{ ruby }}.0/gems/{{ name }}-{{ version }}/ext/{{ e }} clean
    #   {%- endfor -%}
    #   && gem unpack {{ name }}-{{ version }}.gem
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    # - {{ compiler("cxx") }}
  host:
    - ruby
    # - libffi  # [osx]
    # - make  # [osx]
  run:
    - ruby
    # - {{ compiler("c") }}
    # - {{ compiler("cxx") }}

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT & BSD-2-Clause
  license_file: LICENSE
  summary: Cool.io provides a high performance event framework for Ruby which uses the libev C library
  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/tarcieri/cool.io

extra:
  recipe-maintainers:
    - oblute
    - benhuff
    - sodre
