{% set name = "cool.io" %}
{% set version = "1.7.0" %}

package: 
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: a9d35041d5f073cbeb3b12f8111f1dabd2948d8670fd4a248f534069d2af03c8

build:
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
      {%- for e in [ "cool.io", "iobuffer" ] -%}
      && make -C {{ PREFIX }}/lib/ruby/gems/{{ ruby }}.0/gems/{{ name }}-{{ version }}/ext/{{ e }} clean
      {%- endfor -%}
      && gem unpack {{ name }}-{{ version }}.gem
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - ruby
  run:
    - ruby

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT & BSD-2-Clause
  license_file: LICENSE
  summary: Cool.io provides a high performance event framework for Ruby which uses the libev C library
  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/tarcieri/cool.io

extra:
  recipe-maintainers:
    - oblute
    - benhuff
    - sodre
