travis:
  secure:
    BINSTAR_TOKEN: XV6UzjZMF1Rfha6Gh6Ki4B32GPpgEG+1GEfJfhsGof7eQ6B6P1qBvtBh6k8NKeAiuy4LQ8SRy9GI1OiKdyeErZfpqp8VMXU9JloCfWBlX5Bo2pdx6tKKwz1+xF9OoAC/uGh4HszHOwCBI06MuF1VM9P8Xyz5R2BNpsnJmWxLN0CyhKccSTO0OU6KY2Z4kj1JC2qnyXM++Xe/GQlNjtF/3u7FT7irZEutMDSuA0PKX6Rqhn4Uhvnld9alLtdpmp83zn5TedFPfp47fmkY+P2zeHogkgyk9fEZ0pisKcLpMeyDAPEzv4MmN0J/v1u0pJ4gmHqIjHCfqa0PU254nO9mphYfwCBlDoZwAkJ4Jk+SEZbtPGdIYXKKa3L4+tnIu0HvYnD5zmWRSPtoWfJ8Ya4iuWHqWxcN0UdCOkyTrRpNU4H/zrqKi6Yn3gKyuChRZ65IdFkPiBtBU0bNKU2JdFj+iux9bFDfWqoJIXpkqNuUM0zT1r6lWGNk69CmNLo88Xf06Ltk6BzcA7E+sCmZDkWVi/+x8dV5FNyDoSqjsJRT2Km2pP05tlffR+M7gNelAvnUbpjGkJ4UEYXN7KW9W7m2IxGp1AfpMJ7W/7QqfIOSjQcXAmJCSWIlk+ad2gvKbpBt9Gldm4QDY1EVH12nLaXxKj5GtJk+6F6LBmRFFYe8H4o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
